### PR TITLE
Add support for MPEG2 low sampling frequencies (#12)

### PR DESCRIPTION
**Pull request by steinhae**
MPEG2 contains 3 work items, this commit adds support for the first work item i.e. low sampling frequencies. This enables the user to play mp3 audio files produced by e.g. Google Text to Speech API or Amazon Polly.

I added a test mp3 that I produced via AWS Polly. I also tested the commit with various other MPEG2 encoded files. 
Open points: 
- Do we need to add tests to cover this new commit?
- Intensity stereo probably won't work due to the scale factor parsing. I haven't found a test file for this. 
- MPEG2 multi channel (work item 2 of the MPEG2 standard) is not supported. However, there is currently no check present to prevent the playback of such files.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
This is duplicated with #12 .

**Comment by hajimehoshi** [comment]
TBH I created copying the existing PDMP3 implementation, so I'm not so familiar with MP3 implementation. Let's merge this and wait and see!

> Do we need to add tests to cover this new commit?
> Intensity stereo probably won't work due to the scale factor parsing. I haven't found a test file for this.

Ideally yes, but we don't have any tests so far.

> MPEG2 multi channel (work item 2 of the MPEG2 standard) is not supported. However, there is currently no check present to prevent the playback of such files.

Acknowledged.

**Comment by hajimehoshi** [comment]
@steinhae What is the license of mpeg2.mp3?

**Comment by steinhae** [comment]
Thanks for merging.

> @steinhae What is the license of mpeg2.mp3?

I created this file via AWS Polly with lyrics from a youtube video. Not sure about the copyright situation of lyrics. Let's replace it to be sure. I'll provide a new file.

**Pull request merged**
