### PR TITLE
Expose Position() method

### PR DESCRIPTION
**Pull request by yega**
Often need to know the current position in the file.

### CODE REVIEW

**Comment by hajimehoshi** [comment]
Hi,

You can get the position by `n, err := stream.Seek(0, io.SeekCurrent)`

**Comment by yega** [comment]
But why not add particular method for that case? Fewer words are better readable.

**Comment by hajimehoshi** [comment]
Now I'm curious what kind of position you need. I think there are two types of position:

1. How many bytes are read from the source stream
2. How many bytes are decoded
3. How many bytes are read from the decoded stream

All are different not. There might be some remaining bytes that are not decoded yet, or some remaining bytes that are decoded but not read from the user.

If you want 1) or 3), you can call `Seek`, or if you want avoid the cost of `Seek`, you can count bytes by creating an `io.Reader` wrapper, and I think this is not what go-mp3 should do. For 2), this is an internal implementation detail and I don't want to expose this.

**Comment by gonutz** [comment]
As said above, Seek(0, io.SeekCurrent) is the standard way to tell the position of a io.Seeker and it suffices. Adding wrapper functions for every little thing might seem like no big deal but it really is. Consider the doc page for this library, you can read it in a minute and have all the information in a very compact form. Increasing the API by adding "noise" functions like Position will make the library harder to understand and maintain.

Once you add a function you have to keep it to be backward compatible, adding functions is easy but removing them is hard. Thus a minimal API is preferrable.

The Position function adds cost without adding benefit. You can already do the thing and the io.Seeker is as precise as it gets about what it does and returns. Would Position return a byte offset, a number of samples, number of stereo samples? Seek returns byte offsets, you can divide by 2 or 4 to get the other information. No decision to make here.

The io.Seeker is known by Go programmers, it has been around and can be used with existing libraries, thus is was the perfect choice for this library to use it here.

For these reasons I vote to close this issue/pull request.

**Pull request closed without merging**
